name: test run workflow

on:
  pull_request:
    branches: [master]

  push:
    branches: [master]

jobs:

  test-feature:
    runs-on: macOS-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setupjdk
        uses: actions/setup-java@v3

        with:
          java-version: "17"
          distribution: 'adopt'

      - name: gradle permission
        run : chmod +x gradlew

      - name: run test with gradle
        run : ./gradlew test



















